import { MarkerType } from '@vue-flow/core'

export const initialNodes = [
  {
    id: '1',
    type: 'input',
    data: { label: '【完成】（QDLKJ2024-0806004）王淼(总调)创建 2024-07-28 13：23：22' },
    position: { x: 50, y: 0 },
    class: 'light',
  },
  // {
  //   id: '2',
  //   type: 'output',
  //   data: { label: 'Node 2' },
  //   position: { x: 100, y: 100 },
  //   class: 'light',
  // },
  {
    id: '3',
    data: { label: '【完成】王淼（分调）调度 2024-08-12 15:12:34' },
    position: { x: 350, y: 150 },
    class: 'light',
  },
  {
    id: '4',
    data: { label: '【等待】邵杰(主管)审批业务确认' },
    position: { x: 300, y: 300 },
    class: 'light',
  },
  {
    id: '5',
    data: { label: '未执行，司机确认' },
    position: { x: 250, y: 450 },
    class: 'light',
  },
  {
    id: '6',
    data: { label: '未执行，出车确认' },
    position: { x: 200, y: 600 },
    class: 'light',
  },
]

export const initialEdges = [
  // {
  //   id: 'e1-2',
  //   source: '1',
  //   target: '2',
  //   animated: true,
  // },
  {
    id: 'e1-3',
    type: 'smoothstep',
    source: '1',
    target: '3',
    label: '已指派> 王淼 于2024-08-13 13:25:10',
    labelBgStyle: { fill: '#11E6F9' },
    style: {stroke:'#11E6F9'},
    markerEnd: MarkerType.ArrowClosed,
  },
  {
    id: 'e3-4',
    type: 'smoothstep',
    source: '3',
    target: '4',
    labelBgStyle: { fill: '#11E6F9' },
    style: {stroke:'red'},
    label: '已指派> 邵杰 于2024-08-13 13:25:10',
    animated: true,
    markerEnd: MarkerType.ArrowClosed,
  },
    {
    id: 'e4-5',
    type: 'smoothstep',
    source: '4',
    target: '5',
    label: '等待',
    style: { stroke: 'grey' },
    labelBgStyle: { fill: 'grey' },
  },
    {
    id: 'e4-6',
    type: 'smoothstep',
    source: '5',
    target: '1',
    label: '等待',
    style: { stroke: 'grey' },
    labelBgStyle: { fill: 'grey' },
      markerEnd: MarkerType.ArrowClosed,
  },
  {
    id: 'e4-7',
        type:'smoothstep',
    source: '5',
    target: '6',
    label: '等待',
    style: { stroke: 'grey' },
    labelBgStyle: { fill: 'grey' },
    markerEnd: MarkerType.ArrowClosed,
  },
    {
    id: 'e4-8',
    type:'smoothstep',
    source: '6',
    target: '1',
    label: '等待',
    style: { stroke: 'grey' },
    labelBgStyle: { fill: 'grey' },
      markerEnd: MarkerType.ArrowClosed,
  },
]
